// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8cc00ef2-66ba-4d06-afdb-e8d828c35070";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAttackStatusChange();

float humidityValue;
float temperatureValue;
int lightIntensityValue;
int moistureValue;
bool attackStatus;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidityValue, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperatureValue, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(lightIntensityValue, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(moistureValue, READ, 5 * SECONDS, NULL);
  ArduinoCloud.addProperty(attackStatus, READWRITE, ON_CHANGE, onAttackStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
